FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o upvest-api-publisher ./cmd/upvest-api-publisher


FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/upvest-api-publisher .

EXPOSE 8080

CMD ["./upvest-api-publisher"]
